baseURL = "https://pagehelper.github.io/" # "http://mybatis.tk/pagehelper/"
languageCode = "zh-CN"
title = "MyBatis 分页插件 PageHelper"
theme = "kube"
description = ""
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "liuzh" # add your company name
  github = "abel533" # add your github profile name
  twitter = "" # add your twitter profile
  email = "abel533@gmail.com"

[[menu.main]]
    name = "文档"
    weight = 10
    url = "/docs/"
[[menu.main]]
    name = "更新日志"
    weight = 20
    url = "/blog/"
[[menu.main]]
    name = "常见问题"
    weight = 50
    url = "/faq/"
